# requires the following secrets:
# KEPTN_BASE_URL
# KEPTN_API_TOKEN

keptn-automation-demo:
  image: dtdemos/keptn-automation:0.5.0
  variables:
    EVALUATION_RULE: ignore
    KEPTN_PROJECT: slo-demo
    KEPTN_SERVICE: casdemoapp
    KEPTN_STAGE: production
    LABELS: "GitLabJob=$CI_JOB_NAME,executedBy=GitLab,GitLabUrl=$CI_PIPELINE_URL"
  script: |
    echo "-------------------------------------------------------"
    echo "keptn version"
    echo "-------------------------------------------------------"
    keptn version
    echo "-------------------------------------------------------"
    echo "keptn auth"
    echo "-------------------------------------------------------"
    keptn auth -e $KEPTN_BASE_URL/api -a $KEPTN_API_TOKEN
    echo "-------------------------------------------------------"
    echo "keptn status"
    echo "-------------------------------------------------------"
    keptn status
    echo "-------------------------------------------------------"
    echo "keptn get projects"
    echo "-------------------------------------------------------"
    keptn get projects
    echo "-------------------------------------------------------"
    echo "keptn get services --project slo-demo"
    echo "-------------------------------------------------------"
    keptn get services --project slo-demo
    echo "-------------------------------------------------------"
    echo "Running slo-evaluation.sh"
    echo "-------------------------------------------------------"
    slo-evaluation.sh