# requires the following secrets:
# KEPTN_BASE_URL
# KEPTN_API_TOKEN
# DT_BASE_URL
# DT_API_TOKEN
# requires the following secrets:


name: Keptn Onboard Service
on:
  workflow_dispatch:

env:
  KEPTN_PROJECT: dt-orders
  KEPTN_SERVICE: frontend
  KEPTN_STAGE: staging
  KEPTN_SHIPYARD_FILE: ./keptn/shipyard.yaml
  KEPTN_SLO_FILE: ./keptn/slo.yaml
  CONFIGURE_DT_MONITORING: true
  DT_CONF_FILE: ./keptn/dynatrace.conf.yaml
  DT_SLI_FILE: ./keptn/sli.yaml
  DEBUG: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dtdemos/keptn-automation:0.4.0
      env:
        KEPTN_BASE_URL: ${{ secrets.KEPTN_BASE_URL }}
        KEPTN_API_TOKEN: ${{ secrets.KEPTN_API_TOKEN }}
        KEPTN_SHIPYARD_FILE: ${{ env.KEPTN_SHIPYARD_FILE }}
        KEPTN_PROJECT: ${{ env.KEPTN_PROJECT }}
        KEPTN_SERVICE: ${{ env.KEPTN_SERVICE }}
        KEPTN_STAGE: ${{ env.KEPTN_STAGE }}
        DT_CONF_FILE: ${{ env.DT_CONF_FILE }}
        DT_BASE_URL: ${{ secrets.DT_BASE_URL }}
        DT_API_TOKEN: ${{ secrets.DT_API_TOKEN }}
        DEBUG: ${{ env.DEBUG }}
        
    steps:
      # github automatically creates a volume to the checked out code
      # so we can reference them via ./foldername
      - uses: actions/checkout@v2

      - name: createdynatracesecret
        run: create-dynatrace-secret.sh

      - name: keptn onboardservice
        run: keptn.sh create project $KEPTN_PROJECT --shipyard=$KEPTN_SHIPYARD_FILE

      - name: configure_dynatrace_monitoring_for_project
        run: keptn.sh configure monitoring dynatrace --project=$KEPTN_PROJECT

      - name: create_service
        run: keptn.sh create service $KEPTN_SERVICE --project=$KEPTN_PROJECT

      - name: configure_service_with_dynatrace_query
        run: keptn.sh add-resource --project=$KEPTN_PROJECT --stage=$KEPTN_STAGE --service=$KEPTN_SERVICE --resource=$DT_CONF_FILE --resourceUri=dynatrace/dynatrace.conf.yaml